"""Synth — материализация ``config-evolve/`` для одного evolve-тика (Patch 39).

Создаёт изолированный config-каталог с тремя записями в ``tickers.yaml``
(батч из текущего тика) и копией ``app.yaml`` с изменённым
``mode.backfill_years=1``. Остальные YAML (``metrics``, ``event_types``,
``ocr``, ``llm``) — symlink'и на оригинальные ``config/*.yaml``, чтобы
улучшения метрик попадали в evolve-прогоны без копирования.

Symlinks используются на Linux/macOS. На системах, где они недоступны
(Windows без `dev_mode`), функция упадёт на этапе ``os.symlink`` —
evolve-демон рассчитан только на Linux VPS.

Файл ``tickers.yaml`` переписывается на КАЖДОМ тике; редактирование
руками бессмысленно. Любые operator-only правки идут в основной
``config/tickers.yaml``.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Final

import yaml

from edx.evolve.csv_loader import CompanyRow

SYMLINKED_FILES: Final[tuple[str, ...]] = (
    "metrics.yaml",
    "event_types.yaml",
    "ocr.yaml",
    "llm.yaml",
)
TICKERS_HEADER: Final[str] = (
    "# Auto-generated by `edx evolve tick`. DO NOT edit by hand —\n"
    "# the file is overwritten on every tick. To add a permanent issuer,\n"
    "# edit ../config/tickers.yaml instead.\n"
)


def write_evolve_config(
    batch: list[CompanyRow],
    target_dir: Path = Path("config-evolve"),
    base_dir: Path = Path("config"),
    backfill_years_override: int = 1,
) -> None:
    """Materialise ``target_dir`` for one evolve tick.

    Idempotent: re-running on the same batch produces an identical tree.
    """
    target_dir.mkdir(parents=True, exist_ok=True)

    _write_tickers_yaml(batch, target_dir / "tickers.yaml")
    _write_app_yaml(
        base_dir / "app.yaml",
        target_dir / "app.yaml",
        backfill_years_override,
    )
    _ensure_symlinks(base_dir, target_dir)


def _write_tickers_yaml(
    batch: list[CompanyRow], path: Path
) -> None:
    payload: dict[str, list[dict[str, Any]]] = {
        "tickers": [
            {
                "ticker": c.synthetic_ticker,
                "name": c.name,
                "e_disclosure_id": c.company_id,
                "profile": c.type,
            }
            for c in batch
        ]
    }
    rendered = yaml.safe_dump(
        payload,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    path.write_text(TICKERS_HEADER + rendered, encoding="utf-8")


def _write_app_yaml(
    base_path: Path,
    target_path: Path,
    backfill_years_override: int,
) -> None:
    base_data = yaml.safe_load(base_path.read_text(encoding="utf-8"))
    if not isinstance(base_data, dict):
        raise ValueError(
            f"{base_path}: expected mapping at top level, got {type(base_data).__name__}"
        )
    mode = base_data.setdefault("mode", {})
    if not isinstance(mode, dict):
        raise ValueError(
            f"{base_path}: 'mode' is not a mapping ({type(mode).__name__})"
        )
    mode["backfill_years"] = backfill_years_override
    rendered = yaml.safe_dump(
        base_data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    header = (
        "# Auto-generated by `edx evolve tick` from ../config/app.yaml.\n"
        f"# Override: mode.backfill_years={backfill_years_override}.\n"
    )
    target_path.write_text(header + rendered, encoding="utf-8")


def _ensure_symlinks(base_dir: Path, target_dir: Path) -> None:
    """Create or refresh symlinks for the shared YAML files.

    Uses *relative* targets so the symlink stays valid even if the
    project tree is moved as a whole. If a regular file is already
    sitting at the target, it's removed before the symlink is recreated.
    """
    base_abs = base_dir.resolve()
    target_abs = target_dir.resolve()

    for name in SYMLINKED_FILES:
        link_path = target_dir / name
        # Source path, relative to the symlink itself.
        src_relative = os.path.relpath(base_abs / name, start=target_abs)

        if link_path.is_symlink():
            current = os.readlink(link_path)
            if current == src_relative:
                continue
            link_path.unlink()
        elif link_path.exists():
            link_path.unlink()

        os.symlink(src_relative, link_path)


__all__ = ["write_evolve_config"]
